module.exports = [
  {
    "id": 1,
    "company_name": "Meta",
    "location": "Germany",
    "industry": "Business",
    "credentials_id": 2,
    "created_at": "2022-07-02T05:21:46.489Z",
    "updated_at": "2022-07-02T05:21:46.489Z",
    "title": "Financial Analyst",
    "salary": 30000,
    "job_type": "full-time",
    "description": "Als Financial Analyst (m/w/d) sind Sie Teil des Frankfurter Finanzteams und unterstützen den Chief Accountant und den Finance Director bei Controlling und Accounting Themen. Sie sind verantwortlich für einen reibungslosen Ablauf der Debitorenbuchhaltung und koordinieren dabei die externen Dienstleister. Sie erstellen Reporte für verschiedene Fachbereiche und unterstützen bei der Prozessoptimierung im Bereich Debitorenbuchhaltung. Das operative Controlling mit Soll-/Ist Vergleichen und Bereiche des Sales-Controllings gehören ebenso zu Ihren Aufgaben wie auch die Mitwirkung bei der Kontenabstimmung und die Stammdatenpflege. Bei all Ihren Tätigkeiten arbeiten sie eng mit dem lokalen Sales Team und dem internationalen Billing und Accounting Team zusammen.SKILLS / QUALIFICATION REQUIREMENTS Nach einer kaufmännischen Ausbildung oder einem Studium der Betriebswirtschaft verfügen Sie bereits über Berufserfahrung im Finanz- und Rechnungswesen. Idealerweise haben Sie diese Erfahrung im Medienumfeld und/oder innerhalb eines internationalen Unternehmens gesammelt. Großes Interesse an Zahlen und abteilungsübergreifenden Projekten bringen Sie ebenso mit wie praxiserprobten Umgang mit MS-Office (insbesondere Excel) und SAP FI/CO. Ihre Deutsch- und Englischkenntnisse in Wort und Schrift sind sehr gut. Ihre Arbeit organisieren Sie selbständig und Ihre Arbeitsweise ist zuverlässig, genau und ergebnisorientiert. Interesse am Medium Kino und an der Arbeit in einem internationalen Team sowie hohe Kommunikationsfähigkeit runden Ihr Profil ab. We are proud to be a Disability Confident Employer and we’ll do everything we can to support you during your application. If you need us to make any adjustments to our recruitment process, speak to our recruitment team who will be happy to support you. Accessibility Statement | NBCUnicareers Qualifications/Requirements. Sub-Business International UPI Career Level Experienced City Frankfurt-am-Main",
    "user_employer_id": 1
  },
  {
    "id": 2,
    "company_name": "Microsoft",
    "location": "France",
    "industry": "Business",
    "credentials_id": 2,
    "created_at": "2022-07-02T05:21:46.489Z",
    "updated_at": "2022-07-02T05:21:46.489Z",
    "title": "Software Engineer",
    "salary": 25000,
    "job_type": "full-time",
    "description": "Ekimetrics est leader européen en data science avec + 320 data scientists et +1000 projets depuis 2006. Présents à Paris, Londres, NY et HK, nous menons des projets dans +50 pays et pour tous les secteurs d’activité : services financiers, Retail, Telecom, Santé, etc. Notre mission est d’aider les entreprises à auditer leurs opportunités data, enrichir leur capital analytique, et déployer des solutions actionnables permettant de maximiser leur performance marketing et opérationnelle, et ré-énergiser les business models. Notre focus absolu est de délivrer des gains à court terme, tout en garantissant le développement du capital data de nos clients à long terme. Nous nous engageons à proposer les approches data science les plus avancées, et à construire des pratiques AI éthiques et durables.",
    "user_employer_id": 1
  },
  {
    "id": 3,
    "company_name": "Amazon",
    "location": "United States",
    "industry": "Business",
    "credentials_id": 4,
    "created_at": "2022-07-02T05:21:46.489Z",
    "updated_at": "2022-07-02T05:21:46.489Z",
    "title": "Software Engineer",
    "salary": 15000,
    "job_type": "part-time",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione ex in perspiciatis explicabo dicta, est odio provident reiciendis nisi laborum minima repellat sapiente veniam fuga consectetur molestias eveniet! Inventore, alias? Corrupti impedit sed dicta hic aliquid nobis neque quod ullam! Rem temporibus obcaecati dolorem aperiam excepturi qui iusto similique voluptatibus eligendi asperiores tempora, aliquam adipisci tenetur. Consequatur distinctio commodi iste Reiciendis provident, nostrum quae tempora vitae voluptates rerum quas sit! Assumenda iste voluptatibus beatae, a officia itaque sunt recusandae optio inventore quo sapiente quod molestias quae voluptates soluta expedita ipsam? Minima veritatis modi natus omnis. Ipsa quisquam minus quaerat delectus necessitatibus vel dignissimos quam porro facere. Alias ad consequatur numquam maxime soluta asperiores adipisci nobis aliquam cupiditate id, possimus earum. Harum, similique minima nam dolore voluptatem ullam culpa quisquam vitae repellat accusamus dignissimos explicabo eveniet quia officia eius fugiat tempora omnis maxime illum. Ipsa, placeat excepturi cupiditate ea omnis perferendis",
    "user_employer_id": 2
  },
  {
    "id": 4,
    "company_name": "Amazon",
    "location": "United States",
    "industry": "Business",
    "credentials_id": 4,
    "created_at": "2022-07-02T05:21:46.489Z",
    "updated_at": "2022-07-02T05:21:46.489Z",
    "title": "Front-end Developer",
    "salary": 12000,
    "job_type": "part-time",
    "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione ex in perspiciatis explicabo dicta, est odio provident reiciendis nisi laborum minima repellat sapiente veniam fuga consectetur molestias eveniet! Inventore, alias? Corrupti impedit sed dicta hic aliquid nobis neque quod ullam! Rem temporibus obcaecati dolorem aperiam excepturi qui iusto similique voluptatibus eligendi asperiores tempora, aliquam adipisci tenetur. Consequatur distinctio commodi iste Reiciendis provident, nostrum quae tempora vitae voluptates rerum quas sit! Assumenda iste voluptatibus beatae, a officia itaque sunt recusandae optio inventore quo sapiente quod molestias quae voluptates soluta expedita ipsam? Minima veritatis modi natus omnis. Ipsa quisquam minus quaerat delectus necessitatibus vel dignissimos quam porro facere. Alias ad consequatur numquam maxime soluta asperiores adipisci nobis aliquam cupiditate id, possimus earum. Harum, similique minima nam dolore voluptatem ullam culpa quisquam vitae repellat accusamus dignissimos explicabo eveniet quia officia eius fugiat tempora omnis maxime illum. Ipsa, placeat excepturi cupiditate ea omnis perferendis",
    "user_employer_id": 2
  },
  {
    "id": 5,
    "company_name": "Amazon",
    "location": "United States",
    "industry": "Business",
    "credentials_id": 4,
    "created_at": "2022-07-02T05:21:46.489Z",
    "updated_at": "2022-07-02T05:21:46.489Z",
    "title": "Senior Software Engineer",
    "salary": 45000,
    "job_type": "full-time",
    "description": "description here 5",
    "user_employer_id": 2
  },
  {
    "id": 6,
    "company_name": "Google",
    "location": "United Kingdom",
    "industry": "IT",
    "credentials_id": 5,
    "created_at": "2022-07-02T05:21:46.489Z",
    "updated_at": "2022-07-02T05:21:46.489Z",
    "title": "Sales Specialist",
    "salary": 15000,
    "job_type": "part-time",
    "description": "description here 6",
    "user_employer_id": 3
  },
  {
    "id": 7,
    "company_name": "Google",
    "location": "United Kingdom",
    "industry": "IT",
    "credentials_id": 5,
    "created_at": "2022-07-02T05:21:46.489Z",
    "updated_at": "2022-07-02T05:21:46.489Z",
    "title": "UX Designer",
    "salary": 24000,
    "job_type": "full-time",
    "description": "description here 7",
    "user_employer_id": 3
  }
]
